/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_abcew_audio_AudioActivity */

#include <assert.h>
#include <stdio.h>

#ifndef _Included_com_abcew_audio_AudioActivity
#define _Included_com_abcew_audio_AudioActivity

#ifdef __cplusplus
extern "C" {
#endif

namespace BAudio {


/*
 * Class:     com_abcew_audio_AudioActivity
 * Method:    createEngine
 * Signature: ()V
 */
    JNIEXPORT void JNICALL Java_com_abcew_audio_AudioActivity_createEngine
            (JNIEnv *, jclass);

/*
 * Class:     com_abcew_audio_AudioActivity
 * Method:    createUriAudioPlayer
 * Signature: (Ljava/lang/String;)Z
 */
    JNIEXPORT jboolean JNICALL Java_com_abcew_audio_AudioActivity_createUriAudioPlayer
            (JNIEnv *, jclass, jstring);

/*
 * Class:     com_abcew_audio_AudioActivity
 * Method:    setPlayingUriAudioPlayer
 * Signature: (Z)V
 */
    JNIEXPORT void JNICALL Java_com_abcew_audio_AudioActivity_setPlayingUriAudioPlayer
            (JNIEnv *, jclass, jboolean);

/*
 * Class:     com_abcew_audio_AudioActivity
 * Method:    setChannelMuteUriAudioPlayer
 * Signature: (IZ)V
 */
    JNIEXPORT void JNICALL Java_com_abcew_audio_AudioActivity_setChannelMuteUriAudioPlayer
            (JNIEnv *, jclass, jint, jboolean);

/*
 * Class:     com_abcew_audio_AudioActivity
 * Method:    setChannelSoloUriAudioPlayer
 * Signature: (IZ)V
 */
    JNIEXPORT void JNICALL Java_com_abcew_audio_AudioActivity_setChannelSoloUriAudioPlayer
            (JNIEnv *, jclass, jint, jboolean);

/*
 * Class:     com_abcew_audio_AudioActivity
 * Method:    getNumChannelsUriAudioPlayer
 * Signature: ()I
 */
    JNIEXPORT jint JNICALL Java_com_abcew_audio_AudioActivity_getNumChannelsUriAudioPlayer
            (JNIEnv *, jclass);

/*
 * Class:     com_abcew_audio_AudioActivity
 * Method:    setVolumeUriAudioPlayer
 * Signature: (I)V
 */
    JNIEXPORT void JNICALL Java_com_abcew_audio_AudioActivity_setVolumeUriAudioPlayer
            (JNIEnv *, jclass, jint);

/*
 * Class:     com_abcew_audio_AudioActivity
 * Method:    setMuteUriAudioPlayer
 * Signature: (Z)V
 */
    JNIEXPORT void JNICALL Java_com_abcew_audio_AudioActivity_setMuteUriAudioPlayer
            (JNIEnv *, jclass, jboolean);

/*
 * Class:     com_abcew_audio_AudioActivity
 * Method:    enableStereoPositionUriAudioPlayer
 * Signature: (Z)V
 */
    JNIEXPORT void JNICALL Java_com_abcew_audio_AudioActivity_enableStereoPositionUriAudioPlayer
            (JNIEnv *, jclass, jboolean);

/*
 * Class:     com_abcew_audio_AudioActivity
 * Method:    setStereoPositionUriAudioPlayer
 * Signature: (I)V
 */
    JNIEXPORT void JNICALL Java_com_abcew_audio_AudioActivity_setStereoPositionUriAudioPlayer
            (JNIEnv *, jclass, jint);

/*
 * Class:     com_abcew_audio_AudioActivity
 * Method:    shutdown
 * Signature: ()V
 */
    JNIEXPORT void JNICALL Java_com_abcew_audio_AudioActivity_shutdown
            (JNIEnv *, jclass);
}
#ifdef __cplusplus
}
#endif
#endif
