/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_abcew_audio_RecordActivity */


#include <SLES/OpenSLES.h>
#include <SLES/OpenSLES_Android.h>

#include <stdio.h>
#include <assert.h>

#ifndef _Included_com_abcew_audio_RecordActivity
#define _Included_com_abcew_audio_RecordActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_abcew_audio_RecordActivity
 * Method:    createEngine
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_abcew_audio_RecordActivity_createEngine
  (JNIEnv *, jobject);

/*
 * Class:     com_abcew_audio_RecordActivity
 * Method:    createAudioRecord
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_abcew_audio_RecordActivity_createAudioRecord
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_abcew_audio_RecordActivity
 * Method:    stop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_abcew_audio_RecordActivity_stop
  (JNIEnv *, jobject);

/*
 * Class:     com_abcew_audio_RecordActivity
 * Method:    shutdown
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_abcew_audio_RecordActivity_shutdown
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
